apiVersion: apps/v1
kind: Deployment
metadata:
  name: sanjay-deploy
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: sanjay-container
        image: sanjay2307/myapp:v1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sanjay-np-service
  labels:
    app: myapp
spec:
  selector:
    app: myapp

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
